dark_theme: true
show_controls: true
start_with: ''
mode: chat-instruct
chat_style: messenger 
prompt-default: QA
prompt-notebook: QA
preset: simple-1
max_new_tokens: 200
max_new_tokens_min: 1
max_new_tokens_max: 4096
seed: -1
negative_prompt: ''
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 32768
custom_stopping_strings: ''
auto_max_new_tokens: false
max_tokens_second: 0
ban_eos_token: false
custom_token_bans: ''
add_bos_token: true
skip_special_tokens: true
stream: true
name1: <|im_start|>user 
character: Dima 
instruction_template: Dima 
chat-instruct_command: |-
  Please do not make up answers if you do not have the necessary information. Answer need more information, without adding any other words!  

  <|prompt|>
autoload_model: false
default_extensions:
- gallery
- example
